name: Deploy ICS Files to Cloudflare Workers

# Controls when the workflow will run
on:
  push:
    # branches:
      # - 'main'
    paths:
      - '_db/f2/2022.json'

jobs:
  build:
    uses: sportstimes/f1/.github/workflows/ics.yml@feature/updates-workflows
    site: "f2"