name: Deploy IndyCar ICS Files

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    paths:
      - '_db/indycar/2022.json'

jobs:
  build:
    uses: sportstimes/f1/.github/workflows/ics.yml@feature/updated-workflows
    with:
      site: 'indycar'