name: Deploy IndyCar ICS Files

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    paths:
      - '_db/indycar/2022.json'

jobs:
  build:
    uses: sportstimes/f1/.github/workflows/ics.yml@main
    with:
      site: 'indycar'
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}