name: Deploy MotoGP ICS Files

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    paths:
      - '_db/motogp/2022.json'

jobs:
  build:
    uses: sportstimes/f1/.github/workflows/ics.yml@main
    with:
      site: 'motogp'